In [1]:
# Importing libraries
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("Material Compressive Strength Experimental Data.csv")

In [3]:
df.head()

Material_Quantity_gm  Additive_Catalyst_gm  Ash_Component_gm  Water_Mix_ml  \
0                486.42                180.60             21.26        201.66   
1                133.32                260.14            185.60        175.99   
2                559.97                  2.84            111.76        295.23   
3                391.43                351.05             76.39        299.14   
4                394.78                352.61            194.35        235.54   

   Plasticizer_gm  Moderate_Aggregator  Refined_Aggregator  \
0           16.11              1151.17              708.50   
1            6.27              1090.57             1010.25   
2           11.95              1024.93              810.69   
3           19.00              1134.88              881.34   
4           17.02              1098.24              781.01   

   Formulation_Duration_hrs  Compression_Strength_MPa  
0                    344.43                     79.89  
1                     28.86                     59.80  
2                    237.68                     77.86  
3                    208.81                     71.74  
4                    266.84                     76.07

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6139 entries, 0 to 6138
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Material_Quantity_gm      6030 non-null   float64
 1   Additive_Catalyst_gm      6030 non-null   float64
 2   Ash_Component_gm          6030 non-null   float64
 3   Water_Mix_ml              6030 non-null   float64
 4   Plasticizer_gm            6030 non-null   float64
 5   Moderate_Aggregator       6030 non-null   float64
 6   Refined_Aggregator        6030 non-null   float64
 7   Formulation_Duration_hrs  6030 non-null   float64
 8   Compression_Strength_MPa  6139 non-null   float64
dtypes: float64(9)
memory usage: 431.8 KB


In [5]:
# Total null value preset in each columns
df.isnull().sum()

Material_Quantity_gm        109
Additive_Catalyst_gm        109
Ash_Component_gm            109
Water_Mix_ml                109
Plasticizer_gm              109
Moderate_Aggregator         109
Refined_Aggregator          109
Formulation_Duration_hrs    109
Compression_Strength_MPa      0
dtype: int64

In [6]:
df = df.fillna(0)

In [7]:
df.isnull().sum()

Material_Quantity_gm        0
Additive_Catalyst_gm        0
Ash_Component_gm            0
Water_Mix_ml                0
Plasticizer_gm              0
Moderate_Aggregator         0
Refined_Aggregator          0
Formulation_Duration_hrs    0
Compression_Strength_MPa    0
dtype: int64

In [8]:
df = df.astype(int)

In [9]:
cdf = df

In [10]:
df.head()

Material_Quantity_gm  Additive_Catalyst_gm  Ash_Component_gm  Water_Mix_ml  \
0                   486                   180                21           201   
1                   133                   260               185           175   
2                   559                     2               111           295   
3                   391                   351                76           299   
4                   394                   352               194           235   

   Plasticizer_gm  Moderate_Aggregator  Refined_Aggregator  \
0              16                 1151                 708   
1               6                 1090                1010   
2              11                 1024                 810   
3              19                 1134                 881   
4              17                 1098                 781   

   Formulation_Duration_hrs  Compression_Strength_MPa  
0                       344                        79  
1                        28                        59  
2                       237                        77  
3                       208                        71  
4                       266                        76

In [11]:
# Applying corelation
corr_matrix = df.corr()

In [12]:
corr_matrix

Material_Quantity_gm  Additive_Catalyst_gm  \
Material_Quantity_gm                  1.000000              0.070800   
Additive_Catalyst_gm                  0.070800              1.000000   
Ash_Component_gm                      0.040785              0.089000   
Water_Mix_ml                          0.191480              0.135982   
Plasticizer_gm                        0.107269              0.170504   
Moderate_Aggregator                   0.254407              0.142042   
Refined_Aggregator                    0.211725              0.140199   
Formulation_Duration_hrs              0.126436              0.194346   
Compression_Strength_MPa              0.113331              0.169663   

                          Ash_Component_gm  Water_Mix_ml  Plasticizer_gm  \
Material_Quantity_gm              0.040785      0.191480        0.107269   
Additive_Catalyst_gm              0.089000      0.135982        0.170504   
Ash_Component_gm                  1.000000      0.108811        0.189922   
Water_Mix_ml                      0.108811      1.000000        0.093112   
Plasticizer_gm                    0.189922      0.093112        1.000000   
Moderate_Aggregator               0.156351      0.455493        0.144461   
Refined_Aggregator                0.163935      0.371361        0.173292   
Formulation_Duration_hrs          0.144447      0.142538        0.187234   
Compression_Strength_MPa          0.081788     -0.040146        0.193658   

                          Moderate_Aggregator  Refined_Aggregator  \
Material_Quantity_gm                 0.254407            0.211725   
Additive_Catalyst_gm                 0.142042            0.140199   
Ash_Component_gm                     0.156351            0.163935   
Water_Mix_ml                         0.455493            0.371361   
Plasticizer_gm                       0.144461            0.173292   
Moderate_Aggregator                  1.000000            0.554778   
Refined_Aggregator                   0.554778            1.000000   
Formulation_Duration_hrs             0.167630            0.144288   
Compression_Strength_MPa            -0.044303           -0.029335   

                          Formulation_Duration_hrs  Compression_Strength_MPa  
Material_Quantity_gm                      0.126436                  0.113331  
Additive_Catalyst_gm                      0.194346                  0.169663  
Ash_Component_gm                          0.144447                  0.081788  
Water_Mix_ml                              0.142538                 -0.040146  
Plasticizer_gm                            0.187234                  0.193658  
Moderate_Aggregator                       0.167630                 -0.044303  
Refined_Aggregator                        0.144288                 -0.029335  
Formulation_Duration_hrs                  1.000000                  0.253853  
Compression_Strength_MPa                  0.253853                  1.000000

In [13]:
threshold = 0.5
for row in range (len(corr_matrix)):
    for col in range (row):
        if abs((corr_matrix.iloc[row][col])) > threshold:   
             print(corr_matrix.iloc[row][col])
             print(corr_matrix.columns[row]) 

0.5547783135105027
Refined_Aggregator


In [14]:
cdf = cdf.drop('Refined_Aggregator', axis=1)

In [15]:
cdf.head()

Material_Quantity_gm  Additive_Catalyst_gm  Ash_Component_gm  Water_Mix_ml  \
0                   486                   180                21           201   
1                   133                   260               185           175   
2                   559                     2               111           295   
3                   391                   351                76           299   
4                   394                   352               194           235   

   Plasticizer_gm  Moderate_Aggregator  Formulation_Duration_hrs  \
0              16                 1151                       344   
1               6                 1090                        28   
2              11                 1024                       237   
3              19                 1134                       208   
4              17                 1098                       266   

   Compression_Strength_MPa  
0                        79  
1                        59  
2                        77  
3                        71  
4                        76

In [16]:
# Applying Variance
from sklearn.feature_selection import VarianceThreshold

In [17]:
varT = VarianceThreshold()

In [18]:
x = varT.fit_transform(cdf)
x

array([[ 486,  180,   21, ..., 1151,  344,   79],
       [ 133,  260,  185, ..., 1090,   28,   59],
       [ 559,    2,  111, ..., 1024,  237,   77],
       ...,
       [ 358,   22,   17, ..., 1081,  302,   56],
       [ 445,  275,  178, ...,  865,  374,   58],
       [ 560,  266,  167, ..., 1165,  360,   58]])

In [19]:
op = varT.fit(cdf)
op.get_support()

array([ True,  True,  True,  True,  True,  True,  True,  True])

In [20]:
x = cdf[['Material_Quantity_gm', 'Additive_Catalyst_gm', 'Ash_Component_gm',
       'Water_Mix_ml', 'Plasticizer_gm', 'Moderate_Aggregator',
        'Formulation_Duration_hrs',]].values

In [21]:
x

array([[ 486,  180,   21, ...,   16, 1151,  344],
       [ 133,  260,  185, ...,    6, 1090,   28],
       [ 559,    2,  111, ...,   11, 1024,  237],
       ...,
       [ 358,   22,   17, ...,   34, 1081,  302],
       [ 445,  275,  178, ...,   18,  865,  374],
       [ 560,  266,  167, ...,   10, 1165,  360]])

In [22]:
y = cdf["Compression_Strength_MPa"].values

In [23]:
y

array([79, 59, 77, ..., 56, 58, 58])

In [24]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x, y, test_size = 0.20, random_state = 100)

In [25]:
print("Training dataset size [IV]", x_train.shape)
print("Training dataset size [DV]", y_train.shape)
print("Testing dataset size [IV]", x_test.shape)
print("Testing dataset size [DV]", y_test.shape)

Training dataset size [IV] (4911, 7)
Training dataset size [DV] (4911,)
Testing dataset size [IV] (1228, 7)
Testing dataset size [DV] (1228,)


In [26]:
from sklearn import linear_model
regressor = linear_model.LinearRegression()

In [27]:
from sklearn.preprocessing import PolynomialFeatures
poly = PolynomialFeatures(degree=3)

In [28]:
x_train_poly = poly.fit_transform(x_train)

In [29]:
regressor.fit(x_train_poly, y_train)

LinearRegression()

In [30]:
x_test_poly = poly.fit_transform(x_test)
y_hat = regressor.predict(x_test_poly)

In [31]:
from sklearn.metrics import r2_score
print("R2 Score is :", r2_score(y_test, y_hat)*100)

R2 Score is : 36.05251549781112


In [32]:
import pickle
pickle.dump(regressor, open('model.pkl','wb'))
